#include "dmg.h"

lr35902::lr35902() {

    using p = lr35902;
                   //x0                                  x1                              x2                                x3                                x4                               x5                               x6                                  x7                                   x8                               x9                                xA                                xB                                  xC                              xD                                     xE                                xF
    instlist = {
/*0x*/  {"NOP", "", "", &p::NOP, 4},       {"LD", "BC", "d16", &p::LDw, 12},{"LD", "(BC)", "A", &p::LD, 8},  {"INC", "BC", "", &p::INCw, 8}, {"INC", "B", "", &p::INC, 4},        {"DEC", "B", "", &p::DEC, 4},     {"LD", "B", "d8", &p::LD, 8},      {"RLCA", "", "", &p::RLCA, 4},   {"LD", "(a16)", "SP", &p::LDsp, 20},{"ADD", "HL", "BC", &p::ADDw, 8},{"LD", "A", "(BC)", &p::LD, 8},   {"DEC", "BC", "", &p::DECw, 8},      {"INC", "C", "", &p::INC, 4},       {"DEC", "C", "", &p::DEC, 4},      {"LD", "C", "d8", &p::LD, 8},     {"RRCA", "", "", &p::RRCA, 4},
/*1x*/  {"STOP", "", "", &p::STOP, 4},     {"LD", "DE", "d16", &p::LDw, 12},{"LD", "(DE)", "A", &p::LD, 8},  {"INC", "DE", "", &p::INCw, 8}, {"INC", "D", "", &p::INC, 4},        {"DEC", "D", "", &p::DEC, 4},     {"LD", "D", "d8", &p::LD, 8},      {"RLA", "", "", &p::RLA, 4},     {"JR", "r8", "", &p::JR, 12},       {"ADD", "HL", "DE", &p::ADDw, 8},{"LD", "A", "(DE)", &p::LD, 8},   {"DEC", "DE", "", &p::DECw, 8},      {"INC", "E", "", &p::INC, 4},       {"DEC", "E", "", &p::DEC, 4},      {"LD", "E", "d8", &p::LD, 8},     {"RRA", "", "", &p::RRA, 4},
/*2x*/  {"JR", "NZ", "r8", &p::JR, 12},    {"LD", "HL", "d16", &p::LDw, 12},{"LD", "(HL+)", "A", &p::LD, 8}, {"INC", "HL", "", &p::INCw, 8}, {"INC", "H", "", &p::INC, 4},        {"DEC", "H", "", &p::DEC, 4},     {"LD", "H", "d8", &p::LD, 8},      {"DAA", "", "", &p::DAA, 4},     {"JR", "Z", "r8", &p::JR, 12},      {"ADD", "HL", "HL", &p::ADDw, 8},{"LD", "A", "(HL+)", &p::LD, 8},  {"DEC", "HL", "", &p::DECw, 8},      {"INC", "L", "", &p::INC, 4},       {"DEC", "L", "", &p::DEC, 4},      {"LD", "L", "d8", &p::LD, 8},     {"CPL", "", "", &p::CPL},
/*3x*/  {"JR", "NC", "r8", &p::JR, 12},    {"LD", "SP", "d16", &p::LDw, 12},{"LD", "(HL-)", "A", &p::LD, 8}, {"INC", "SP", "", &p::INCw, 8}, {"INC", "(HL)", "", &p::INC, 12},    {"DEC", "(HL)", "", &p::DEC, 12}, {"LD", "(HL)", "d8", &p::LD, 12},  {"SCF", "", "", &p::SCF, 4},     {"JR", "Ca", "r8", &p::JR, 12},     {"ADD", "HL", "SP", &p::ADDw, 8},{"LD", "A", "(HL-)",&p::LD, 8},   {"DEC", "SP", "", &p::DECw, 8},      {"INC", "A", "", &p::INC, 4},       {"DEC", "A", "", &p::DEC, 4},      {"LD", "A", "d8", &p::LD, 8},     {"CCF", "", "", &p::CCF, 4},
/*4x*/  {"LD", "B", "B", &p::LD, 4},       {"LD", "B", "C", &p::LD, 4},     {"LD", "B", "D", &p::LD, 4},     {"LD", "B", "E", &p::LD, 4},    {"LD", "B", "H", &p::LD, 4},         {"LD", "B", "L", &p::LD, 4},      {"LD", "B", "(HL)", &p::LD, 8},    {"LD", "B", "A", &p::LD, 4},     {"LD", "C", "B", &p::LD, 4},        {"LD", "C", "C", &p::LD, 4},     {"LD", "C", "D", &p::LD, 4},      {"LD", "C", "E", &p::LD, 4},         {"LD", "C", "H", &p::LD, 4},        {"LD", "C", "L", &p::LD, 4},       {"LD", "C", "(HL)", &p::LD, 8},   {"LD", "C", "A", &p::LD, 4},
/*5x*/  {"LD", "D", "B", &p::LD, 4},       {"LD", "D", "C", &p::LD, 4},     {"LD", "D", "D", &p::LD, 4},     {"LD", "D", "E", &p::LD, 4},    {"LD", "D", "H", &p::LD, 4},         {"LD", "D", "L", &p::LD, 4},      {"LD", "D", "(HL)", &p::LD, 8},    {"LD", "D", "A", &p::LD, 4},     {"LD", "E", "B", &p::LD, 4},        {"LD", "E", "C", &p::LD, 4},     {"LD", "E", "D", &p::LD, 4},      {"LD", "E", "E", &p::LD, 4},         {"LD", "E", "H", &p::LD, 4},        {"LD", "E", "L", &p::LD, 4},       {"LD", "E", "(HL)", &p::LD, 8},   {"LD", "E", "A", &p::LD, 4},
/*6x*/  {"LD", "H", "B", &p::LD, 4},       {"LD", "H", "C", &p::LD, 4},     {"LD", "H", "D", &p::LD, 4},     {"LD", "H", "E", &p::LD, 4},    {"LD", "H", "H", &p::LD, 4},         {"LD", "H", "L", &p::LD, 4},      {"LD", "H", "(HL)", &p::LD, 8},    {"LD", "H", "A", &p::LD, 4},     {"LD", "L", "B", &p::LD, 4},        {"LD", "L", "C", &p::LD, 4},     {"LD", "L", "D", &p::LD, 4},      {"LD", "L", "E", &p::LD, 4},         {"LD", "L", "H", &p::LD, 4},        {"LD", "L", "L", &p::LD, 4},       {"LD", "L", "(HL)", &p::LD, 8},   {"LD", "L", "A", &p::LD, 4},
/*7x*/  {"LD", "(HL)", "B", &p::LD, 4},    {"LD", "(HL)", "C", &p::LD, 4},  {"LD", "(HL)", "D", &p::LD, 4},  {"LD", "(HL)", "E", &p::LD, 4}, {"LD", "(HL)", "H", &p::LD, 4},      {"LD", "(HL)", "L", &p::LD, 4},   {"HALT", "", "", &p::HALT, 4},     {"LD", "(HL)", "A", &p::LD, 4},  {"LD", "A", "B", &p::LD, 4},        {"LD", "A", "C", &p::LD, 4},     {"LD", "A", "D", &p::LD, 4},      {"LD", "A", "E", &p::LD, 4},         {"LD", "A", "H", &p::LD, 4},        {"LD", "A", "L", &p::LD, 4},       {"LD", "A", "(HL)", &p::LD, 8},   {"LD", "A", "A", &p::LD, 4},
/*8x*/  {"ADD", "A", "B", &p::ADD, 4},     {"ADD", "A", "C", &p::ADD, 4},   {"ADD", "A", "D", &p::ADD, 4},   {"ADD", "A", "E", &p::ADD, 4},  {"ADD", "A", "H", &p::ADD, 4},       {"ADD", "A", "L", &p::ADD, 4},    {"ADD", "A", "(HL)", &p::ADD, 8},  {"ADD", "A", "A", &p::ADD, 4},   {"ADC", "A", "B", &p::ADC, 4},      {"ADC", "A", "C", &p::ADC, 4},   {"ADC", "A", "D", &p::ADC, 4},    {"ADC", "A", "E", &p::ADC, 4},       {"ADC", "A", "H", &p::ADC, 4},      {"ADC", "A", "L", &p::ADC, 4},     {"ADC", "A", "(HL)", &p::ADC, 8}, {"ADC", "A", "A", &p::ADC, 4},
/*9x*/  {"SUB", "B", "", &p::SUB, 4},      {"SUB", "C", "", &p::SUB, 4},    {"SUB", "D", "", &p::SUB, 4},    {"SUB", "E", "", &p::SUB, 4},   {"SUB", "H", "", &p::SUB, 4},        {"SUB", "L", "", &p::SUB, 4},     {"SUB", "(HL)", "", &p::SUB, 8},   {"SUB", "A", "", &p::SUB, 4},    {"SBC", "A", "B", &p::SBC, 4},      {"SBC", "A", "C", &p::SBC, 4},   {"SBC", "A", "D", &p::SBC, 4},    {"SBC", "A", "E", &p::SBC, 4},       {"SBC", "A", "L", &p::SBC, 4},      {"SBC", "A", "L", &p::SBC, 4},     {"SBC", "A", "(HL)", &p::SBC, 8}, {"SBC", "A", "A", &p::SBC, 4}, 
/*Ax*/  {"AND", "B", "", &p::AND, 4},      {"AND", "C", "", &p::AND, 4},    {"AND", "D", "", &p::AND, 4},    {"AND", "E", "", &p::AND, 4},   {"AND", "H", "", &p::AND, 4},        {"AND", "L", "", &p::AND, 4},     {"AND", "(HL)", "", &p::AND, 8},   {"AND", "A", "", &p::AND, 4},    {"XOR", "B", "", &p::XOR, 4},       {"XOR", "C", "", &p::XOR, 4},    {"XOR", "D", "", &p::XOR, 4},     {"XOR", "E", "", &p::XOR, 4},        {"XOR", "H", "", &p::XOR, 4},       {"XOR", "L", "", &p::XOR, 4},      {"XOR", "(HL)", "", &p::XOR, 8},  {"XOR", "A", "", &p::XOR, 4},
/*Bx*/  {"OR", "B", "", &p::OR, 4},        {"OR", "C", "", &p::OR, 4},      {"OR", "D", "", &p::OR, 4},      {"OR", "E", "", &p::OR, 4},     {"OR", "H", "", &p::OR, 4},          {"OR", "L", "", &p::OR, 4},       {"OR", "(HL)", "", &p::OR, 8},     {"OR", "A", "", &p::OR, 4},      {"CP", "B", "", &p::CP, 4},         {"CP", "C", "", &p::CP, 4},      {"CP", "D", "", &p::CP, 4},       {"CP", "E", "", &p::CP, 4},          {"CP", "H", "", &p::CP, 4},         {"CP", "L", "", &p::CP, 4},        {"CP", "(HL)", "", &p::CP, 4},    {"CP", "A", "", &p::CP, 4}, 
/*Cx*/  {"RET", "NZ", "", &p::RET, 20},    {"POP", "BC", "", &p::POP, 12},  {"JP", "NZ", "a16", &p::JP, 16}, {"JP", "a16", "", &p::JP, 16},  {"CALL", "NZ", "a16", &p::CALL, 24}, {"PUSH", "BC", "", &p::PUSH, 16}, {"ADD", "A", "d8", &p::ADD, 8},    {"RST", "00H", "", &p::RST, 16}, {"RET", "Z", "", &p::RET, 20},      {"RET", "", "", &p::RET, 16},    {"JP", "Z", "a16", &p::JP, 16},   {"PREFIX", "CB", "", &p::PREFIX, 4}, {"CALL", "Z", "a16", &p::CALL, 24}, {"CALL", "a16", "", &p::CALL, 24}, {"ADC", "A", "d8", &p::ADC, 8},   {"RST", "08H", "", &p::RST, 16},
/*Dx*/  {"RET", "NC", "", &p::RET, 20},    {"POP", "DE", "", &p::POP, 12},  {"JP", "NC", "a16", &p::JP, 16}, {"???", "", "", nullptr, 0},    {"CALL", "NC", "a16", &p::CALL, 24}, {"PUSH", "DE", "", &p::PUSH, 16}, {"SUB", "d8", "", &p::SUB, 8},     {"RST", "10H", "", &p::RST, 16}, {"RET", "C", "", &p::RET, 20},      {"RETI", "", "", &p::RETI, 16},  {"JP", "C", "a16", &p::JP, 16},   {"???", "", "", nullptr, 0},         {"CALL", "C", "a16", &p::CALL, 24}, {"???", "", "", nullptr, 0},       {"SBC", "A", "d8", &p::SBC, 8},   {"RST", "18H", "", &p::RST, 16},
/*Ex*/  {"LDH", "(a8)", "A", &p::LDH, 12}, {"POP", "HL", "", &p::POP, 12},  {"LD", "(C)", "A", &p::LD, 8},   {"???", "", "", nullptr, 0},    {"CALL", "", "", nullptr, 0},        {"PUSH", "HL", "", &p::PUSH, 0},  {"AND", "d8", "", &p::AND, 8},     {"RST", "20H", "", &p::RST, 16}, {"ADD", "SP", "r8", &p::ADDw, 16},  {"JP", "(HL)", "", &p::JP, 4},   {"LD", "(a16)", "A", &p::LD, 16}, {"???", "", "", nullptr, 0},         {"???", "", "", nullptr, 0},        {"???", "", "", nullptr, 0},       {"XOR", "d8", "", &p::XOR, 8},    {"RST", "28H", "", &p::RST, 16},
/*Fx*/  {"LDH", "A", "(a8)", &p::LDH, 12}, {"POP", "AF", "", &p::POP, 12},  {"LD", "A", "(C)", &p::LD, 8},   {"DI", "", "", &p::DI, 4},      {"???", "", "", nullptr, 0},         {"PUSH", "AF", "", &p::PUSH, 16}, {"OR", "d8", "", &p::OR, 8},       {"RST", "30H", "", &p::RST, 16}, {"LD", "HL", "SP+r8", &p::LD, 12},  {"LD", "SP", "HL", &p::LDw, 8},  {"LD", "A", "(a16)", &p::LDw, 16},{"EI", "", "", &p::EI, 4},           {"???", "", "", nullptr, 0},        {"???", "", "", nullptr, 0},       {"CP", "d8", "", &p::CP, 8},      {"RST", "38H", "", &p::RST, 16}
    }; 
 
    preflist = { 
/*0x*/  {"RLC", "B", "", &p::RLC, 8},      {"RLC", "C", "", &p::RLC, 8},    {"RLC", "D", "", &p::RLC, 8},    {"RLC", "E", "", &p::RLC, 8},   {"RLC", "H", "", &p::RLC, 8},        {"RLC", "L", "", &p::RLC, 8},     {"RLC", "(HL)", "", &p::RLC, 16},  {"RLC", "A", "", &p::RLC, 8},    {"RRC", "B", "", &p::RRC, 8},      {"RRC", "C", "", &p::RRC, 8},    {"RRC", "D", "", &p::RRC, 8},      {"RRC", "E", "", &p::RRC, 8},        {"RRC", "H", "", &p::RRC, 8},      {"RRC", "L", "", &p::RRC, 8},       {"RRC", "(HL)", "", &p::RRC, 16},  {"RRC", "A", "", &p::RRC, 8},
/*1x*/  {"RL", "B", "", &p::RL, 8},        {"RL", "C", "", &p::RL, 8},      {"RL", "D", "", &p::RL, 8},      {"RL", "E", "", &p::RL, 8},     {"RL", "H", "", &p::RL, 8},          {"RL", "L", "", &p::RL, 8},       {"RL", "(HL)", "", &p::RL, 16},    {"RL", "A", "", &p::RL, 8},      {"RR", "B", "", &p::RR, 8},        {"RR", "C", "", &p::RR, 8},      {"RR", "D", "", &p::RR, 8},        {"RR", "E", "", &p::RR, 8},          {"RR", "H", "", &p::RR, 8},        {"RR", "L", "", &p::RR, 8},         {"RR", "(HL)", "", &p::RR, 16},    {"RR", "A", "", &p::RR, 8},
/*2x*/  {"SLA", "B", "", &p::SLA, 8},      {"SLA", "C", "", &p::SLA, 8},    {"SLA", "D", "", &p::SLA, 8},    {"SLA", "E", "", &p::SLA, 8},   {"SLA", "H", "", &p::SLA, 8},        {"SLA", "L", "", &p::SLA, 8},     {"SLA", "(HL)", "", &p::SLA, 16},  {"SLA", "A", "", &p::SLA, 8},    {"SRA", "B", "", &p::SRA, 8},      {"SRA", "C", "", &p::SRA, 8},    {"SRA", "D", "", &p::SRA, 8},      {"SRA", "E", "", &p::SRA, 8},        {"SRA", "H", "", &p::SRA, 8},      {"SRA", "L", "", &p::SRA, 8},       {"SRA", "(HL)", "", &p::SRA, 16},  {"SRA", "A", "", &p::SRA, 8},
/*3x*/  {"SWAP", "B", "", &p::SWAP, 8},    {"SWAP", "C", "", &p::SWAP, 8},  {"SWAP", "D", "", &p::SWAP, 8},  {"SWAP", "E", "", &p::SWAP, 8}, {"SWAP", "H", "", &p::SWAP, 8},      {"SWAP", "L", "", &p::SWAP, 8},   {"SWAP", "(HL)", "", &p::SWAP, 16},{"SWAP", "A", "", &p::SWAP, 8},  {"SRL", "B", "", &p::SRL, 8},      {"SRL", "C", "", &p::SRL, 8},    {"SRL", "D", "", &p::SRL, 8},      {"SRL", "E", "", &p::SRL, 8},        {"SRL", "H", "", &p::SRL, 8},      {"SRL", "L", "", &p::SRL, 8},       {"SRL", "(HL)", "", &p::SRL, 16},  {"SRL", "A", "", &p::SRL, 8},
/*4x*/  {"BIT", "0", "B", &p::BIT, 8},     {"BIT", "0", "C", &p::BIT, 8},   {"BIT", "0", "D", &p::BIT, 8},   {"BIT", "0", "E", &p::BIT, 8},  {"BIT", "0", "H", &p::BIT, 8},       {"BIT", "0", "L", &p::BIT, 8},    {"BIT", "0", "(HL)", &p::BIT, 16}, {"BIT", "0", "A", &p::BIT, 8},   {"BIT", "1", "B", &p::BIT, 8},     {"BIT", "1", "C", &p::BIT, 8},   {"BIT", "1", "D", &p::BIT, 8},     {"BIT", "1", "E", &p::BIT, 8},       {"BIT", "1", "H", &p::BIT, 8},     {"BIT", "1", "L", &p::BIT, 8},      {"BIT", "1", "(HL)", &p::BIT, 16}, {"BIT", "1", "A", &p::BIT, 8},     
/*5x*/  {"BIT", "2", "B", &p::BIT, 8},     {"BIT", "2", "C", &p::BIT, 8},   {"BIT", "2", "D", &p::BIT, 8},   {"BIT", "2", "E", &p::BIT, 8},  {"BIT", "2", "H", &p::BIT, 8},       {"BIT", "2", "L", &p::BIT, 8},    {"BIT", "2", "(HL)", &p::BIT, 16}, {"BIT", "2", "A", &p::BIT, 8},   {"BIT", "3", "B", &p::BIT, 8},     {"BIT", "3", "C", &p::BIT, 8},   {"BIT", "3", "D", &p::BIT, 8},     {"BIT", "3", "E", &p::BIT, 8},       {"BIT", "3", "H", &p::BIT, 8},     {"BIT", "3", "L", &p::BIT, 8},      {"BIT", "3", "(HL)", &p::BIT, 16}, {"BIT", "3", "A", &p::BIT, 8},
/*6x*/  {"BIT", "4", "B", &p::BIT, 8},     {"BIT", "4", "C", &p::BIT, 8},   {"BIT", "4", "D", &p::BIT, 8},   {"BIT", "4", "E", &p::BIT, 8},  {"BIT", "4", "H", &p::BIT, 8},       {"BIT", "4", "L", &p::BIT, 8},    {"BIT", "4", "(HL)", &p::BIT, 16}, {"BIT", "4", "A", &p::BIT, 8},   {"BIT", "5", "B", &p::BIT, 8},     {"BIT", "5", "C", &p::BIT, 8},   {"BIT", "5", "D", &p::BIT, 8},     {"BIT", "5", "E", &p::BIT, 8},       {"BIT", "5", "H", &p::BIT, 8},     {"BIT", "5", "L", &p::BIT, 8},      {"BIT", "5", "(HL)", &p::BIT, 16}, {"BIT", "5", "A", &p::BIT, 8},
/*7x*/  {"BIT", "6", "B", &p::BIT, 8},     {"BIT", "6", "C", &p::BIT, 8},   {"BIT", "6", "D", &p::BIT, 8},   {"BIT", "6", "E", &p::BIT, 8},  {"BIT", "6", "H", &p::BIT, 8},       {"BIT", "6", "L", &p::BIT, 8},    {"BIT", "6", "(HL)", &p::BIT, 16}, {"BIT", "6", "A", &p::BIT, 8},   {"BIT", "7", "B", &p::BIT, 8},     {"BIT", "7", "C", &p::BIT, 8},   {"BIT", "7", "D", &p::BIT, 8},     {"BIT", "7", "E", &p::BIT, 8},       {"BIT", "7", "H", &p::BIT, 8},     {"BIT", "7", "L", &p::BIT, 8},      {"BIT", "7", "(HL)", &p::BIT, 16}, {"BIT", "7", "A", &p::BIT, 8},
/*8x*/  {"RES", "0", "B", &p::RES, 8},     {"RES", "0", "C", &p::RES, 8},   {"RES", "0", "D", &p::RES, 8},   {"RES", "0", "E", &p::RES, 8},  {"RES", "0", "H", &p::RES, 8},       {"RES", "0", "L", &p::RES, 8},    {"RES", "0", "(HL)", &p::RES, 16}, {"RES", "0", "A", &p::RES, 8},   {"RES", "1", "B", &p::RES, 8},     {"RES", "1", "C", &p::RES, 8},   {"RES", "1", "D", &p::RES, 8},     {"RES", "1", "E", &p::RES, 8},       {"RES", "1", "H", &p::RES, 8},     {"RES", "1", "L", &p::RES, 8},      {"RES", "1", "(HL)", &p::RES, 16}, {"RES", "1", "A", &p::RES, 8},     
/*9x*/  {"RES", "2", "B", &p::RES, 8},     {"RES", "2", "C", &p::RES, 8},   {"RES", "2", "D", &p::RES, 8},   {"RES", "2", "E", &p::RES, 8},  {"RES", "2", "H", &p::RES, 8},       {"RES", "2", "L", &p::RES, 8},    {"RES", "2", "(HL)", &p::RES, 16}, {"RES", "2", "A", &p::RES, 8},   {"RES", "3", "B", &p::RES, 8},     {"RES", "3", "C", &p::RES, 8},   {"RES", "3", "D", &p::RES, 8},     {"RES", "3", "E", &p::RES, 8},       {"RES", "3", "H", &p::RES, 8},     {"RES", "3", "L", &p::RES, 8},      {"RES", "3", "(HL)", &p::RES, 16}, {"RES", "3", "A", &p::RES, 8},
/*Ax*/  {"RES", "4", "B", &p::RES, 8},     {"RES", "4", "C", &p::RES, 8},   {"RES", "4", "D", &p::RES, 8},   {"RES", "4", "E", &p::RES, 8},  {"RES", "4", "H", &p::RES, 8},       {"RES", "4", "L", &p::RES, 8},    {"RES", "4", "(HL)", &p::RES, 16}, {"RES", "4", "A", &p::RES, 8},   {"RES", "5", "B", &p::RES, 8},     {"RES", "5", "C", &p::RES, 8},   {"RES", "5", "D", &p::RES, 8},     {"RES", "5", "E", &p::RES, 8},       {"RES", "5", "H", &p::RES, 8},     {"RES", "5", "L", &p::RES, 8},      {"RES", "5", "(HL)", &p::RES, 16}, {"RES", "5", "A", &p::RES, 8},
/*Bx*/  {"RES", "6", "B", &p::RES, 8},     {"RES", "6", "C", &p::RES, 8},   {"RES", "6", "D", &p::RES, 8},   {"RES", "6", "E", &p::RES, 8},  {"RES", "6", "H", &p::RES, 8},       {"RES", "6", "L", &p::RES, 8},    {"RES", "6", "(HL)", &p::RES, 16}, {"RES", "6", "A", &p::RES, 8},   {"RES", "7", "B", &p::RES, 8},     {"RES", "7", "C", &p::RES, 8},   {"RES", "7", "D", &p::RES, 8},     {"RES", "7", "E", &p::RES, 8},       {"RES", "7", "H", &p::RES, 8},     {"RES", "7", "L", &p::RES, 8},      {"RES", "7", "(HL)", &p::RES, 16}, {"RES", "7", "A", &p::RES, 8},
/*Cx*/  {"SET", "0", "B", &p::SET, 8},     {"SET", "0", "C", &p::SET, 8},   {"SET", "0", "D", &p::SET, 8},   {"SET", "0", "E", &p::SET, 8},  {"SET", "0", "H", &p::SET, 8},       {"SET", "0", "L", &p::SET, 8},    {"SET", "0", "(HL)", &p::SET, 16}, {"SET", "0", "A", &p::SET, 8},   {"SET", "1", "B", &p::SET, 8},     {"SET", "1", "C", &p::SET, 8},   {"SET", "1", "D", &p::SET, 8},     {"SET", "1", "E", &p::SET, 8},       {"SET", "1", "H", &p::SET, 8},     {"SET", "1", "L", &p::SET, 8},      {"SET", "1", "(HL)", &p::SET, 16}, {"SET", "1", "A", &p::SET, 8},     
/*Dx*/  {"SET", "2", "B", &p::SET, 8},     {"SET", "2", "C", &p::SET, 8},   {"SET", "2", "D", &p::SET, 8},   {"SET", "2", "E", &p::SET, 8},  {"SET", "2", "H", &p::SET, 8},       {"SET", "2", "L", &p::SET, 8},    {"SET", "2", "(HL)", &p::SET, 16}, {"SET", "2", "A", &p::SET, 8},   {"SET", "3", "B", &p::SET, 8},     {"SET", "3", "C", &p::SET, 8},   {"SET", "3", "D", &p::SET, 8},     {"SET", "3", "E", &p::SET, 8},       {"SET", "3", "H", &p::SET, 8},     {"SET", "3", "L", &p::SET, 8},      {"SET", "3", "(HL)", &p::SET, 16}, {"SET", "3", "A", &p::SET, 8},
/*Ex*/  {"SET", "4", "B", &p::SET, 8},     {"SET", "4", "C", &p::SET, 8},   {"SET", "4", "D", &p::SET, 8},   {"SET", "4", "E", &p::SET, 8},  {"SET", "4", "H", &p::SET, 8},       {"SET", "4", "L", &p::SET, 8},    {"SET", "4", "(HL)", &p::SET, 16}, {"SET", "4", "A", &p::SET, 8},   {"SET", "5", "B", &p::SET, 8},     {"SET", "5", "C", &p::SET, 8},   {"SET", "5", "D", &p::SET, 8},     {"SET", "5", "E", &p::SET, 8},       {"SET", "5", "H", &p::SET, 8},     {"SET", "5", "L", &p::SET, 8},      {"SET", "5", "(HL)", &p::SET, 16}, {"SET", "5", "A", &p::SET, 8},
/*Fx*/  {"SET", "6", "B", &p::SET, 8},     {"SET", "6", "C", &p::SET, 8},   {"SET", "6", "D", &p::SET, 8},   {"SET", "6", "E", &p::SET, 8},  {"SET", "6", "H", &p::SET, 8},       {"SET", "6", "L", &p::SET, 8},    {"SET", "6", "(HL)", &p::SET, 16}, {"SET", "6", "A", &p::SET, 8},   {"SET", "7", "B", &p::SET, 8},     {"SET", "7", "C", &p::SET, 8},   {"SET", "7", "D", &p::SET, 8},     {"SET", "7", "E", &p::SET, 8},       {"SET", "7", "H", &p::SET, 8},     {"SET", "7", "L", &p::SET, 8},      {"SET", "7", "(HL)", &p::SET, 16}, {"SET", "7", "A", &p::SET, 8},
    };

    r8list = {
        {"A", &af.a}, {"F", &af.f},
        {"B", &bc.b}, {"C", &bc.c},
        {"D", &de.d}, {"E", &de.e},
        {"H", &hl.h}, {"L", &hl.l}
    };

    r16list = {
        {"AF", (uint16_t *) &af},
        {"BC", (uint16_t *) &bc},
        {"DE", (uint16_t *) &de},
        {"HL", (uint16_t *) &hl},
        {"PC", (uint16_t *) &pc},
        {"SP", (uint16_t *) &sp}
    };

    op8list = {"A", "F", "B", "C", "D", "E", "H", "L", "d8", "(a8)", "(a16)", "(HL)", "(HL+)", "(HL-)", "(C)", "Z", "NZ", "Ca", "NC"};
    op16list = {"AF", "BC", "DE", "HL", "SP", "PC", "a16", "d16", "SP+r8"};
}